### ISSUE TITLE
CPU inference results of yolov5 are wrong

### ISSUE THREAD

**Issue by syn0419** [ultralytics/yolov5#12225]
### Search before asking

- [X] I have searched the YOLOv5 [issues](https://github.com/ultralytics/yolov5/issues) and [discussions](https://github.com/ultralytics/yolov5/discussions) and found no similar questions.

### Question

I inferenced with the model trained on Multi-GPUs，the results is right when I use GPU , but when I set "--device cpu”，I got wrong results (too many boxes predicted, and all confidence is 1) .I am sure I use the same image and same checkpoint. After investigation, I found the model parameter values of some layer are different when I inference with CPU and GPU. But the parameters are all same of the ckpt loaded in both way. I don't know why

**Comment by glenn-jocher** [comment]
@syn0419 hi there,

Thank you for reaching out and bringing this issue to our attention.

Inference results can sometimes differ when switching between GPU and CPU due to various factors, including numerical precision differences and optimizations specific to each device.

To investigate further, could you please provide the following information:

1. The command you used for inference with CPU (`--device cpu`).
2. The command you used for inference with GPU.
3. The specific layer(s) where you noticed differences in the model parameter values between CPU and GPU inference.
4. Any additional details that may help us reproduce the issue.

Meanwhile, please ensure that you have followed the recommended installation instructions and have the latest versions of all required dependencies installed.

Thank you for your cooperation. We'll do our best to assist you further and resolve this issue.

Best,

**Comment by syn0419** [comment]
@glenn-jocher  
Thank you so much for your answer.
1. The command I used for inference with CPU is:  `python detect.py --weights  /YOLOs/yolov5/runs/train/yolov5s_train2/weights/best.pt --source /YOLOs/yolov5/data_demo/images --data data/custom.yaml --device cpu --conf-thres 0.45 --iou-thres 0.5`
2. The command I used for inference with GPU is:  `python detect.py --weights  /YOLOs/yolov5/runs/train/yolov5s_train2/weights/best.pt --source /YOLOs/yolov5/data_demo/images --data data/custom.yaml --device 0 --conf-thres 0.45 --iou-thres 0.5`
3. Through check I found the values of four parameters are different between CPU and GPU inference：
    (1) the parameters value of the conv layer after the third C3
    (2) the parameters value of the conv in the fourth C3 
    (3) the parameters value of  the conv in SPPF
    (4) bias in last C3
The difference occurs later in the parameter，like 
![image](https://github.com/ultralytics/yolov5/assets/49259869/127e16b4-e479-4155-a88a-1be0503d8c34)
4. I clone the git several months ago
the official requirement like:
![image](https://github.com/ultralytics/yolov5/assets/49259869/1727e95b-5919-45ff-8910-df7604d7de29)

My environment like:
absl-py==1.4.0
addict==2.4.0
attrs==23.1.0
cached-property==1.5.2
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.5.7
charset-normalizer==3.2.0
cmake==3.26.4
coloredlogs==15.0.1
contourpy==1.1.0
coremltools==7.0
cycler==0.11.0
dm-tree==0.1.8
exceptiongroup==1.1.3
filelock==3.12.2
flatbuffers==23.5.26
fonttools==4.41.0
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==1.0.0
grpcio==1.56.2
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.0
Jinja2==3.1.2
joblib==1.3.2
jstyleson==0.0.2
kiwisolver==1.4.4
libclang==16.0.6
lit==16.0.6
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.5
networkx==3.1
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.2.5.6
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.2.140
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.2.140
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.4.25
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
nvidia-pyindex==1.0.9
nvidia-tensorrt==99.0.0
oauthlib==3.2.2
onnx==1.13.0
onnx-simplifier==0.4.33
onnxruntime==1.15.1
opencv-python==4.8.0.74
openvino-telemetry==2023.1.1
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
protobuf==3.20.3
psutil==5.9.5
pyaml==23.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycocotools==2.0.6
Pygments==2.16.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.5.3
rsa==4.9
scikit-learn==1.1.2
scipy==1.10.1
seaborn==0.12.2
six==1.16.0
smmap==5.0.0
sympy==1.12
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.34.0
tensorrt==8.6.1.post1
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
termcolor==2.3.0
texttable==1.6.7
thop==0.1.1.post2209072238
threadpoolctl==3.2.0
toolz==0.12.0
torch==1.7.1+cu101
torchaudio==0.7.2
torchvision==0.8.2+cu101
tqdm==4.65.0
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
ultralytics==8.0.136
urllib3==1.26.16
Werkzeug==2.3.6
wrapt==1.15.0
wurlitzer==3.0.3
zipp==3.16.2

Thanks for your help!  Best wishes!

**Comment by glenn-jocher** [comment]
@syn0419 

Thank you for providing the details and sharing your environment information.

Based on your description, it seems that there is a difference in the parameter values of certain layers when using CPU and GPU for inference in YOLOv5.

The difference in parameter values can occur due to several factors, including numerical precision differences and optimizations specific to each device (CPU or GPU).

However, it's important to note that these differences in parameter values do not necessarily indicate a problem or error. The model parameters can vary slightly between devices, but the overall performance and accuracy of the model should remain consistent.

If you are observing significant differences in model performance or accuracy between CPU and GPU inference, please provide more information and specific examples, such as input images and their corresponding output predictions, along with any logs or error messages you may have encountered. This will help us further investigate and assist you more effectively.

In the meantime, please ensure that you have followed the recommended installation instructions and have the latest versions of all required dependencies installed.

Please feel free to reach out if you have any further questions or concerns. We are here to help.

Thank you for your understanding and cooperation.

**Comment by syn0419** [comment]
@glenn-jocher 
Thank you for your replay. 

The problem is that the overall performance and accuracy of the model  are inconsistent when I infer on CPU and GPU.

At first I found the results are different when I infer on CPU and GPU:
![image](https://github.com/ultralytics/yolov5/assets/49259869/2fd03652-6b25-4b71-a88a-b74e27607076)

Then, I found "pred" the output of the model are different between CPU and GPU. After check , I found Individual parameters are different when I infer on CPU and GPU as mentioned above. 

And there is no error messages either on CPU and GPU. Both soutput the result successfully.

I don't understand why parameter values are different on different devices. 

I have no idea about the different overall performance between CPU and GPU as images I provided above

And, the checkpoint I used to inference was trained in Torch 1.7.1, do I need to retrain the model if I upgrade the environment?

Thanks for your help! Best wishes!

**Comment by glenn-jocher** [comment]
@syn0419 

Thank you for providing additional details.

I understand that you are observing inconsistent performance and accuracy when inferring on CPU and GPU with YOLOv5. You have shared images illustrating the difference in results as well as the individual parameter values.

The differences in parameter values between CPU and GPU inference can occur due to numerical precision variations and optimizations specific to each device. However, it's concerning that this is leading to inconsistent overall performance and accuracy for your model.

To further investigate and assist you, it would be helpful if you could provide the following information:

1. The specific commands you used for training the model.
2. Any additional information regarding the training dataset, augmentation techniques, and training configurations you used.
3. Example images and their corresponding annotations from your dataset that demonstrate the inconsistent performance of the model between CPU and GPU.
4. Details about the hardware specifications of your CPU and GPU devices.
5. Any relevant logs, error messages, or warnings during training or inference.

Regarding your question about upgrading the environment, it is generally recommended to use the same environment for training and inference to ensure consistency. However, upgrading the environment should not require retraining the model unless there are significant changes in the dependencies that impact the model's functionality.

Please provide the requested information to help us further diagnose the issue and provide appropriate guidance. We apologize for any inconvenience this may have caused and appreciate your patience.

Thank you for your cooperation. We are here to assist you.

**Comment by syn0419** [comment]
@glenn-jocher
Thank you for your patience.

Maybe I don't need to provide training information because I found that the same problem occurs on the official pretrained model yolov5s. 
![image](https://github.com/ultralytics/yolov5/assets/49259869/7554df8b-de77-4557-8d4c-85b6195dfba8)

And the different parameter values between CPU and GPU occured in the same conv layers (the 26th, 28th, 32th, 55th conv) as I use the model I trained.
I mistakenly thought that the last different parameter value was the 55th bias before, but it is also a convolutional layer (the 55th convolutional layer)

The CPU I used
![image](https://github.com/ultralytics/yolov5/assets/49259869/345bff80-83e3-473b-8c12-70815a93566a)

The GPU I used
![image](https://github.com/ultralytics/yolov5/assets/49259869/5712be2a-fdf7-4fdf-8a3a-428b61273d40)

![image](https://github.com/ultralytics/yolov5/assets/49259869/294e3c85-a2f7-4747-a235-921bcf3f2a61)

The information displayed when I infer with CPU
![image](https://github.com/ultralytics/yolov5/assets/49259869/cfcb264b-4b6f-4c59-9410-4285baa637b2)

The information displayed when I infer with GPU
![image](https://github.com/ultralytics/yolov5/assets/49259869/1e50ba93-5cbe-4479-a51d-4ec5e71d3ed6)

Perhaps I should try changing the environment and retry, to see if the same issue persists. 

Thank you for your help. Best Wishes!

**Comment by glenn-jocher** [comment]
@syn0419 

Thank you for providing the additional information and images.

I understand that you have observed the same problem of inconsistent parameter values between CPU and GPU in the official pretrained yolov5s model. The parameter differences occur in specific convolutional layers (26th, 28th, 32nd, and 55th conv).

The CPU and GPU devices you used have different specifications, which may contribute to the variation in parameter values. To further investigate and troubleshoot the issue, you mentioned that you plan to change the environment and retry the inference to see if the problem persists.

I recommend taking the following steps:

1. Ensure that you have the latest versions of all required dependencies installed.
2. Double-check the installation instructions and verify that you followed them correctly for both CPU and GPU environments.
3. Verify that you are using the same model checkpoints and script versions for CPU and GPU inference.
4. If possible, try running the inference on different devices within the same category (i.e., different CPUs or different GPUs) to determine if the issue is specific to a particular device.

These steps will help identify if the problem is related to specific hardware configurations or inconsistencies in the setup.

Thank you for bringing this issue to our attention. If you encounter any further challenges or have additional information to share, please don't hesitate to reach out. We are here to assist you.

Best wishes!

**Comment by syn0419** [comment]
@glenn-jocher
Thank you for your advice.

I modified my running environment and I found both the final results and parameter values are same between CPU and GPU.  Nothing unusual occurred in this new environment. 

The new environment is a docker container created  with the method from reference website [https://docs.ultralytics.com/quickstart/#conda-docker-image](url). And I ran on the same devices as before.

It seems that this is indeed caused by the environment. However, I still don't understand the principles involved.

Thank you again for your help. Best wishes!

**Comment by glenn-jocher** [comment]
@syn0419 thank you for your update.

I'm glad to hear that after modifying your running environment and using a docker container, you found that both the final results and parameter values are now consistent between CPU and GPU. It's good to know that the issue was related to the environment and has been resolved.

The specific principles behind the differences in parameter values between CPU and GPU devices can be quite complex and depend on various factors, including numerical precision and optimizations specific to each device. In general, these variations can occur due to differences in hardware architectures, software optimizations, or even slight variations in floating-point arithmetic implementations.

Although the exact details may be challenging to pinpoint, what matters most is that the model's performance and accuracy are now consistent across different devices with the updated environment.

If you have any further questions or encounter any other issues, please don't hesitate to reach out. We are here to assist you.

Best regards,

**Comment by syn0419** [comment]
@glenn-jocher
Thank you for your patient guidance.

In fact, I re-ran the experiments in the same environment but on different devices. I redeployed the same environment on my laptop as the previous machine (with some minor differences, but theoretically I think they should not affect the results). I found that the results obtained by running it on my laptop were also fine.

In fact, I still don't have a clear understanding of what exactly affected the results.

**1. Origin environment(Environment with incorrect results)**
absl-py==1.4.0
addict==2.4.0
attrs==23.1.0
cached-property==1.5.2
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.5.7
charset-normalizer==3.2.0
cmake==3.26.4
coloredlogs==15.0.1
contourpy==1.1.0
coremltools==7.0
cycler==0.11.0
dm-tree==0.1.8
exceptiongroup==1.1.3
filelock==3.12.2
flatbuffers==23.5.26
fonttools==4.41.0
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==1.0.0
grpcio==1.56.2
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.0
Jinja2==3.1.2
joblib==1.3.2
jstyleson==0.0.2
kiwisolver==1.4.4
libclang==16.0.6
lit==16.0.6
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.5
networkx==3.1
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.2.5.6
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.2.140
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.2.140
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.4.25
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
nvidia-pyindex==1.0.9
nvidia-tensorrt==99.0.0
oauthlib==3.2.2
onnx==1.13.0
onnx-simplifier==0.4.33
onnxruntime==1.15.1
opencv-python==4.8.0.74
openvino-telemetry==2023.1.1
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
protobuf==3.20.3
psutil==5.9.5
pyaml==23.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycocotools==2.0.6
Pygments==2.16.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.5.3
rsa==4.9
scikit-learn==1.1.2
scipy==1.10.1
seaborn==0.12.2
six==1.16.0
smmap==5.0.0
sympy==1.12
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.34.0
tensorrt==8.6.1.post1
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
termcolor==2.3.0
texttable==1.6.7
thop==0.1.1.post2209072238
threadpoolctl==3.2.0
toolz==0.12.0
torch==1.7.1+cu101
torchaudio==0.7.2
torchvision==0.8.2+cu101
tqdm==4.65.0
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
ultralytics==8.0.136
urllib3==1.26.16
Werkzeug==2.3.6
wrapt==1.15.0
wurlitzer==3.0.3
zipp==3.16.2

**2. Environment deployed on my laptop**
absl-py==1.4.0
addict==2.4.0
attrs==23.1.0
cached-property==1.5.2
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.5.7
charset-normalizer==3.2.0
cmake==3.27.7
coloredlogs==15.0.1
contourpy==1.1.0
coremltools==7.0
cycler==0.11.0
dm-tree==0.1.8
exceptiongroup==1.1.3
filelock==3.12.2
flatbuffers==23.5.26
fonttools==4.41.0
# fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==1.0.0
grpcio==1.56.2
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.0
Jinja2==3.1.2
joblib==1.3.2
jstyleson==0.0.2
kiwisolver==1.4.4
libclang==16.0.6
lit==16.0.6
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.5
networkx==3.1
numpy==1.24.3
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.2.140
nvidia-nvtx-cu12==12.1.105
nvidia-pyindex==1.0.9
nvidia-tensorrt==99.0.0
oauthlib==3.2.2
opencv-python==4.8.0.74
openvino-telemetry==2023.1.1
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
protobuf==3.20.3
psutil==5.9.5
py-cpuinfo==9.0.0
pyaml==23.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
Pygments==2.16.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.5.3
rsa==4.9
scikit-learn==1.1.2
scipy==1.10.1
seaborn==0.12.2
six==1.16.0
smmap==5.0.0
sympy==1.12
tensorrt==8.6.1.post1
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
termcolor==2.3.0
texttable==1.6.7
thop==0.1.1.post2209072238
threadpoolctl==3.2.0
toolz==0.12.0
torch==1.7.1+cu101
torchaudio==0.7.2
torchvision==0.8.2+cu101
tqdm==4.65.0
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
ultralytics==8.0.136
urllib3==1.26.16
Werkzeug==2.3.6
wrapt==1.15.0
wurlitzer==3.0.3
zipp==3.17.0

Thank you again for your help. Best wishes!

**Comment by syn0419** [comment]
@glenn-jocher
Thank you for your patient guidance.

In fact, I re-ran the experiments in the same environment but on different devices. I redeployed the same environment on my laptop as the previous machine (with some minor differences, but theoretically I think they should not affect the results). I found that the results obtained by running it on my laptop were also fine.

In fact, I still don't have a clear understanding of what exactly affected the results.

1. Origin environment(Environment with incorrect results)
absl-py==1.4.0
addict==2.4.0
attrs==23.1.0
cached-property==1.5.2
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.5.7
charset-normalizer==3.2.0
cmake==3.26.4
coloredlogs==15.0.1
contourpy==1.1.0
coremltools==7.0
cycler==0.11.0
dm-tree==0.1.8
exceptiongroup==1.1.3
filelock==3.12.2
flatbuffers==23.5.26
fonttools==4.41.0
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==1.0.0
grpcio==1.56.2
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.0
Jinja2==3.1.2
joblib==1.3.2
jstyleson==0.0.2
kiwisolver==1.4.4
libclang==16.0.6
lit==16.0.6
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.5
networkx==3.1
numpy==1.24.3
nvidia-cublas-cu11==11.10.3.66
nvidia-cublas-cu12==12.2.5.6
nvidia-cuda-cupti-cu11==11.7.101
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-nvrtc-cu12==12.2.140
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cuda-runtime-cu12==12.2.140
nvidia-cudnn-cu11==8.5.0.96
nvidia-cudnn-cu12==8.9.4.25
nvidia-cufft-cu11==10.9.0.58
nvidia-curand-cu11==10.2.10.91
nvidia-cusolver-cu11==11.4.0.1
nvidia-cusparse-cu11==11.7.4.91
nvidia-nccl-cu11==2.14.3
nvidia-nvtx-cu11==11.7.91
nvidia-pyindex==1.0.9
nvidia-tensorrt==99.0.0
oauthlib==3.2.2
onnx==1.13.0
onnx-simplifier==0.4.33
onnxruntime==1.15.1
opencv-python==4.8.0.74
openvino-telemetry==2023.1.1
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
protobuf==3.20.3
psutil==5.9.5
pyaml==23.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycocotools==2.0.6
Pygments==2.16.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.5.3
rsa==4.9
scikit-learn==1.1.2
scipy==1.10.1
seaborn==0.12.2
six==1.16.0
smmap==5.0.0
sympy==1.12
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.34.0
tensorrt==8.6.1.post1
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
termcolor==2.3.0
texttable==1.6.7
thop==0.1.1.post2209072238
threadpoolctl==3.2.0
toolz==0.12.0
torch==1.7.1+cu101
torchaudio==0.7.2
torchvision==0.8.2+cu101
tqdm==4.65.0
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
ultralytics==8.0.136
urllib3==1.26.16
Werkzeug==2.3.6
wrapt==1.15.0
wurlitzer==3.0.3
zipp==3.16.2

2. Environment deployed on my laptop
absl-py==1.4.0
addict==2.4.0
attrs==23.1.0
cached-property==1.5.2
cachetools==5.3.1
cattrs==23.1.2
certifi==2023.5.7
charset-normalizer==3.2.0
cmake==3.27.7
coloredlogs==15.0.1
contourpy==1.1.0
coremltools==7.0
cycler==0.11.0
dm-tree==0.1.8
exceptiongroup==1.1.3
filelock==3.12.2
flatbuffers==23.5.26
fonttools==4.41.0

fsspec==2023.9.2
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.22.0
google-auth-oauthlib==1.0.0
grpcio==1.56.2
humanfriendly==10.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.0
Jinja2==3.1.2
joblib==1.3.2
jstyleson==0.0.2
kiwisolver==1.4.4
libclang==16.0.6
lit==16.0.6
Markdown==3.4.3
markdown-it-py==3.0.0
MarkupSafe==2.1.3
matplotlib==3.7.2
mdurl==0.1.2
mpmath==1.3.0
msgpack==1.0.5
networkx==3.1
numpy==1.24.3
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.18.1
nvidia-nvjitlink-cu12==12.2.140
nvidia-nvtx-cu12==12.1.105
nvidia-pyindex==1.0.9
nvidia-tensorrt==99.0.0
oauthlib==3.2.2
opencv-python==4.8.0.74
openvino-telemetry==2023.1.1
packaging==23.1
pandas==2.0.3
Pillow==10.0.0
protobuf==3.20.3
psutil==5.9.5
py-cpuinfo==9.0.0
pyaml==23.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
Pygments==2.16.1
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0
requests==2.31.0
requests-oauthlib==1.3.1
rich==13.5.3
rsa==4.9
scikit-learn==1.1.2
scipy==1.10.1
seaborn==0.12.2
six==1.16.0
smmap==5.0.0
sympy==1.12
tensorrt==8.6.1.post1
tensorrt-bindings==8.6.1
tensorrt-libs==8.6.1
termcolor==2.3.0
texttable==1.6.7
thop==0.1.1.post2209072238
threadpoolctl==3.2.0
toolz==0.12.0
torch==1.7.1+cu101
torchaudio==0.7.2
torchvision==0.8.2+cu101
tqdm==4.65.0
triton==2.0.0
typing_extensions==4.5.0
tzdata==2023.3
ultralytics==8.0.136
urllib3==1.26.16
Werkzeug==2.3.6
wrapt==1.15.0
wurlitzer==3.0.3
zipp==3.17.0

Thank you again for your help. Best wishes!

**Comment by glenn-jocher** [comment]
@syn0419 thank you for providing the detailed information about your environments and the results of your experiments.

It's interesting to note that when you ran the experiments on different devices but within the same environment, the results were consistent. This suggests that the inconsistencies you observed previously may have been related to specific hardware configurations or other factors unique to the previous machine.

While the specific factors influencing the parameter values between CPU and GPU devices can be complex, the important outcome is that the results are now consistent across different devices using the updated environment.

Thank you for sharing this information and your experience. If you have any further questions or need additional assistance, please let us know. We're here to help!

**Comment by syn0419** [comment]
@glenn-jocher 
Thank you again for your patience. Best wishes!

**Comment by glenn-jocher** [comment]
@syn0419

Thank you for your kind words and best wishes. I'm glad I could assist you. If you have any further questions or need assistance in the future, please feel free to reach out. Take care and have a great day!
